version: '3.8'

services:

  moodle:
    build: 
      context: .  # Context is the project root
      dockerfile: moodle/Dockerfile
    volumes:
      - ./moodle:/var/www/html
      - ./data/moodledata:/var/www/moodledata
    ports:
      - "8080:80"
    environment:
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle_db
      MOODLE_DB_USER: root
      MOODLE_DB_PASS: example
    depends_on:
      - db

  db:
    image: mariadb:10.6.7
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/db-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: moodle_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: example

volumes:
  moodledata:
  db:
